# Generated by Django 3.2.9 on 2021-11-26 18:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_financetype'),
    ]

    operations = [
        migrations.CreateModel(
            name='Searches',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search', models.CharField(db_index=True, max_length=200)),
                ('display', models.CharField(db_index=True, max_length=500)),
                ('account', models.CharField(db_index=True, max_length=50)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fin_category', to='finances.categories')),
                ('finance_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fin_type', to='finances.financetype')),
            ],
        ),
    ]
