# Generated by Django 3.2.9 on 2022-01-03 22:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_auto_20211126_1117'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankentry',
            options={'verbose_name': 'Bank Entry', 'verbose_name_plural': 'Bank Entries'},
        ),
        migrations.AlterModelOptions(
            name='categories',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='financetype',
            options={'verbose_name': 'Finance Type', 'verbose_name_plural': 'Finance Types'},
        ),
        migrations.AlterModelOptions(
            name='searches',
            options={'verbose_name': 'Search', 'verbose_name_plural': 'Searches'},
        ),
    ]
